### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by lasario** [Philantrop/calibre-marvin-manager#54]
Searched issue theads and could not find a solution to this issue.

calibre, version 1.39.0
ERROR: Error: Error communicating with device

Metadata object has no attribute named: 'has_cover'

Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 86, in run
  File "site-packages\calibre\gui2\device.py", line 571, in _upload_books
  File "C:\Users\todds\AppData\Local\Temp\calibre__rk725\u9xqqa_ios_local_db\Marvin_overlays.py", line 1553, in upload_books
  File "C:\Users\todds\AppData\Local\Temp\calibre__rk725\u9xqqa_ios_local_db\Marvin_overlays.py", line 1382, in _upload_subset
  File "C:\Users\todds\AppData\Local\Temp\calibre__rk725\u9xqqa_ios_local_db\Marvin_overlays.py", line 1734, in _create_new_book
  File "site-packages\calibre\ebooks\metadata\book\base.py", line 149, in __getattribute__
AttributeError: Metadata object has no attribute named: 'has_cover'

**Comment by Philantrop** [comment]
No response, closing.
