### ISSUE TITLE
Restoring Backup fails with AttributeError "tuple object has no attribute toUtf8"

### ISSUE THREAD

**Issue by clarkgflipper** [Philantrop/calibre-marvin-manager#58]
iOS 8.0.2
Mac OS X 10.9.5
Marvin 2.7.6
calibre 2.5
Marvin XD 1.2.4
iPad Air

Step 1: Create backup using Marvin XD.
Step 2: Try to restore it.

![marvinxderror](https://cloud.githubusercontent.com/assets/8972123/4603510/caf9217e-516e-11e4-8c63-062d298b013d.png)

**Comment by digitalhuman** [comment]
Same problem here when trying to convert EPUB to MOBI.
```

calibre, version 3.40.1
ERROR: Unhandled exception: <b>AttributeError</b>:'tuple' object has no attribute 'format'

calibre 3.40.1 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "site-packages\calibre\gui2\actions\convert.py", line 160, in convert_ebook
  File "site-packages\calibre\gui2\actions\convert.py", line 177, in do_convert
  File "site-packages\calibre\gui2\tools.py", line 124, in convert_single_ebook
AttributeError: 'tuple' object has no attribute 'format'

```

**Comment by Philantrop** [comment]
This plugin has been dead for years now. Nothing to see here, move on.
